#!/usr/bin/env python3

# ------------------------------------------------------------------------------
# Orca / Prusa / Super Slicer post-processor script for the Professional Firmware
# AML 2.0 Support
# URL: https://github.com/mriscoc/Ender3V2S1
# Miguel A. Risco-Castillo
# version: 3.2
# date: 2023-12-10
#
# Contains code from the jpg re-encoder thumbnail post processor script:
# github.com/alexqzd/Marlin/blob/Gcode-preview/Display%20firmware/gcode_thumb_to_jpg.py
# ------------------------------------------------------------------------------

import sys
import re
import os
import base64 
import io
import subprocess

try:
    from PIL import Image
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow"])
    from PIL import Image
    
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Get the g-code source file name
sourceFile = sys.argv[1]

# Read the ENTIRE g-code file into memory
with open(sourceFile, "r") as f:
    lines = f.read()

thumb_expresion = '; thumbnail begin.*?\n((.|\n)*?); thumbnail end'
size_expresion = '; thumbnail begin [0-9]+x[0-9]+ [0-9]+'
size_expresion_group = '; thumbnail begin [0-9]+x[0-9]+ ([0-9]+)'

thumb_matches = re.findall(thumb_expresion, lines)
size_matches = re.findall(size_expresion, lines)

def encodedStringToGcodeComment(encodedString):
    n = 78
    return '; ' + '\n; '.join(encodedString[i:i+n] for i in range(0, len(encodedString), n)) + '\n'


for idx, match in enumerate(thumb_matches):
    original = match[0]
    encoded = original.replace("; ", "")
    encoded = encoded.replace("\n", "")
    encoded = encoded.replace("\r", "")
    decoded = base64.b64decode(encoded)
    img_png = Image.open(io.BytesIO(decoded))
    img_png_rgb = img_png.convert('RGB')
    img_byte_arr = io.BytesIO()
    img_png_rgb.save(img_byte_arr, format='jpeg')
    img_byte_arr = img_byte_arr.getvalue()
    encodedjpg = base64.b64encode(img_byte_arr).decode("utf-8")
    encodedjpg_gcode = encodedStringToGcodeComment(encodedjpg)
    lines = lines.replace(original, encodedjpg_gcode)

    size_match = size_matches[idx]
    size = re.findall(size_expresion_group, size_match)
    new_size = size_match.replace(size[0], str(len(encodedjpg)))
    lines = lines.replace(size_match, new_size)

#If the thumbnail was already a JPG, reformat block start
lines = lines.replace("thumbnail_JPG", "thumbnail")

#Prepare header values
ph = re.search('; generated by (.*)\n', lines)
if ph is not None : lines = lines.replace(ph[0], "")

time = 0
match = re.search('; estimated printing time \(normal mode\) = (.*)\n', lines, re.IGNORECASE)
if match is not None :
  h = re.search('(\d+)h',match[1])
  h = int(h[1]) if h is not None else 0
  m = re.search('(\d+)m',match[1])
  m = int(m[1]) if m is not None else 0
  s = re.search('(\d+)s',match[1])
  s = int(s[1]) if s is not None else 0
  time = h*3600+m*60+s

match = re.search('; filament used \[mm\] = ([0-9.]+)', lines, re.IGNORECASE)
filament = float(match[1])/1000 if match is not None else 0

match = re.search('; bed_shape = (.*)\n', lines, re.IGNORECASE)
bed_max = list(map(int, match[1].split(',')[2].split('x'))) if match is not None else [220,220]

match = re.search('; first layer print x min = ([0-9.]+)', lines, re.IGNORECASE)
minx = float(match[1]) if match is not None else 0

match = re.search('; first layer print y min = ([0-9.]+)', lines, re.IGNORECASE)
miny = float(match[1]) if match is not None else 0

match = re.search('; first layer print x max = ([0-9.]+)', lines, re.IGNORECASE)
maxx = float(match[1]) if match is not None else 0

match = re.search('; first layer print y max = ([0-9.]+)', lines, re.IGNORECASE)
maxy = float(match[1]) if match is not None else 0

match = re.search('; layer_height = ([0-9.]+)', lines, re.IGNORECASE)
layer = float(match[1]) if match is not None else 0

match = re.search('; first_layer_height = ([0-9.]+)', lines, re.IGNORECASE)
firstlayer = float(match[1]) if match is not None else 0

match = re.search('; total layer count = ([0-9.]+)', lines, re.IGNORECASE)
totlc = float(match[1]) if match is not None else 0

maxz = totlc * layer + firstlayer
minz = 0

#Adaptive Mesh Leveling

match = re.search('; AML mesh density x = ([3-9]+|auto)', lines, re.IGNORECASE)
aml_meshdensityX = match[1] if match is not None else "auto"

match = re.search('; AML mesh density y = ([3-9]+|auto)', lines, re.IGNORECASE)
aml_meshdensityY = match[1] if match is not None else "auto"

match = re.search('; AML mesh density = ([3-9]+|auto)', lines, re.IGNORECASE)
aml_meshdensity = match[1] if match is not None else "auto"

match = re.search('; AML margin = ([0-9.]+)', lines, re.IGNORECASE)
aml_margin = float(match[1]) if match is not None else 5

match = re.search('; AML prime = ([0-1]+)', lines, re.IGNORECASE)
aml_enableprime = (int(match[1]) == 1) if match is not None else False

aml_minx = max(0.5, minx - aml_margin)
aml_miny = max(0.5, miny - aml_margin)
aml_maxx = min(bed_max[0]-0.5, maxx + aml_margin)
aml_maxy = min(bed_max[1]-0.5, maxy + aml_margin)

if aml_meshdensityX=="auto":
  aml_meshdensityX = str(max(3,min(9,round((aml_maxx-aml_minx)/30))))
if aml_meshdensityY=="auto":
  aml_meshdensityY = str(max(3,min(9,round((aml_maxy-aml_miny)/30))))
if aml_meshdensity=="auto":
  aml_meshdensity = min(aml_meshdensityX,aml_meshdensityY)

aml_limits = 'L{:.3f} R{:.3f} F{:.3f} B{:.3f} N{} X{} Y{}'.format(aml_minx, aml_maxx, aml_miny, aml_maxy, aml_meshdensity, aml_meshdensityX, aml_meshdensityY)
aml_lev = '''\nG29 P1  ; new mesh
M420 S1 ; activate leveling
C108    ; close mesh viewer '''
aml_prime = '''\nG1 Z2 F240 ; Moves Z Axis up little to avoid scratching of bed

G1 X237 F15000
M117 Priming...
; Purge hotend of previous filament
G1 E60 F300 ; Extrude 60mm of filament at 300mm/min
G92 E0  ; Reset extruder
G4 P2000
M117 Wiping...
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
G1 X237 F15000
G1 X225 F15000
M117 Printing...
G1 X{0:.3f} Y{1:.3f} F3000 ; Move to start position 
G1 Z{2:.3f} F240 ; Move to layer height
G1 Y{3:.3f} E15 F900 ; line 1
G92 E0  ; Reset extruder
G1 X{4:.3f} E15 F900 ; line 2
G92 E0  ; Reset extruder
G1 Y{1:.3f} E15 F900 ; line 3
G92 E0  ; Reset extruder
G1 X{0:.3f} E15 F900 ; line 4
G92 E0  ; Reset extruder
G1 Z2.0 F3000 ; Moves Z Axis up little to avoid scratching of bed'''.format(aml_minx, aml_miny, layer, aml_maxy, aml_maxx) if aml_enableprime else ""
if (maxx - minx) > 0:
  lines = re.sub(r'(\nC29 *)(A\b)( *.*)', r'\1'+aml_limits+r'\3'+aml_lev+aml_prime, lines)

#Generate output file
try:
    with open(sourceFile, "w+") as of:
    # Write header values
        if ph is not None : of.write(ph[0])
        of.write(';FLAVOR:Marlin\n')
        of.write(';TIME:{:d}\n'.format(time))
        of.write(';Filament used: {:.6f}\n'.format(filament))
        of.write(';Layer height: {:.2f}\n'.format(layer))
        of.write(';MINX:{:.3f}\n'.format(minx))
        of.write(';MINY:{:.3f}\n'.format(miny))
        of.write(';MINZ:{:.3f}\n'.format(minz))
        of.write(';MAXX:{:.3f}\n'.format(maxx))
        of.write(';MAXY:{:.3f}\n'.format(maxy))
        of.write(';MAXZ:{:.3f}\n'.format(maxz))
        of.write(';POSTPROCESSED\n')
        of.write(';Header generated for the MRiscoC Professional Firmware\n')
        of.write(';AML 2.0 support\n')
        of.write(';https://github.com/mriscoc/Ender3V2S1')
        of.write(lines)
except:
    print('Error writing output file')
    input()
finally:
    of.close()
    f.close()
